// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trailer-section/EmbeddedPlayer.tsx": () => import("../components/mockups/trailer-section/EmbeddedPlayer.tsx"),
  "./components/mockups/trailer-section/ModalPlayer.tsx": () => import("../components/mockups/trailer-section/ModalPlayer.tsx"),
  "./components/mockups/trailer-section/TrailerGallery.tsx": () => import("../components/mockups/trailer-section/TrailerGallery.tsx")
};
